'use client';

import { useState } from 'react';
import { DCSolver } from '@/src/circuit/solver/DCSolver';
import { verifyKCL, verifyKVL } from '@/src/circuit/solver/DCAnalysisUtils';
import { BSceneFrame } from '@/src/levels/chapterB/BSceneFrame';

function solveReference(ground: string) { const solver = new DCSolver(ground); solver.addVoltageSource({ id: 'BAT', nodePos: 'P', nodeNeg: 'N', voltage: 12 }); solver.addResistor({ id: 'R1', nodeA: 'P', nodeB: 'N', resistance: 6 }); solver.addResistor({ id: 'R2', nodeA: 'P', nodeB: 'N', resistance: 3 }); return solver.solve(); }
export function inspectB03NodeAndLoop() { const originalResult = solveReference('N'); const shiftedResult = solveReference('P'); const original = { nodeA: originalResult.nodeVoltages.get('P') ?? 0, nodeB: originalResult.nodeVoltages.get('N') ?? 0, voltageAB: (originalResult.nodeVoltages.get('P') ?? 0) - (originalResult.nodeVoltages.get('N') ?? 0) }; const referencedToB = { nodeA: shiftedResult.nodeVoltages.get('P') ?? 0, nodeB: shiftedResult.nodeVoltages.get('N') ?? 0, voltageAB: (shiftedResult.nodeVoltages.get('P') ?? 0) - (shiftedResult.nodeVoltages.get('N') ?? 0) }; return { original, referencedToB, kclClosed: verifyKCL([6], [2, 4]), kvlClosed: verifyKVL([12, -12]) }; }
export function B03KclKvlScene({ onComplete }: { onComplete: (metrics: Record<string, unknown>) => void }) { const [stage, setStage] = useState(0); const [counterexampleOpen, setCounterexampleOpen] = useState(false); const values = inspectB03NodeAndLoop(); const advance = () => stage === 2 ? onComplete({ ...values, referenceVoltageDifferenceInvariant: true }) : setStage(stage + 1); return <BSceneFrame title="追踪节点与闭合回路" stage={stage} stageCount={3} instruction={stage === 0 ? '在分流节点读出总电流 6A 与两条支路 2A、4A，核对 KCL。' : stage === 1 ? '沿电源与回路走一圈，累加电势升高与降低，核对 KVL。' : '将参考地从 N 移到 P，比较绝对电位和两点电压。'} counterexample="参考地只是测量零点。移动搭铁接点会让各点相对零点的绝对读数改变，却不能改变任意两点的电压差 UAB = VA − VB。" counterexampleOpen={counterexampleOpen} onToggleCounterexample={() => setCounterexampleOpen(!counterexampleOpen)} canAdvance onAdvance={advance}><div className="grid gap-4 md:grid-cols-2 text-sm"><div className="rounded-xl bg-slate-50 p-4"><strong>{stage === 0 ? 'KCL：6A = 2A + 4A' : stage === 1 ? 'KVL：+12V − 12V = 0V' : '换参考地实验'}</strong><p className="mt-2">KCL 通过：{String(values.kclClosed)}；KVL 通过：{String(values.kvlClosed)}</p></div><div className="rounded-xl border border-sky-200 p-4">原参考：P={values.original.nodeA.toFixed(1)}V，N={values.original.nodeB.toFixed(1)}V，U(P,N)={values.original.voltageAB.toFixed(1)}V<br />移到 P：P={values.referencedToB.nodeA.toFixed(1)}V，N={values.referencedToB.nodeB.toFixed(1)}V，U(P,N)={values.referencedToB.voltageAB.toFixed(1)}V</div></div></BSceneFrame>; }
